# Generated by Django 5.1 on 2024-09-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineinventory',
            options={'verbose_name': 'MedicineInventory', 'verbose_name_plural': 'MedicineInventory'},
        ),
    ]
