# Generated by Django 5.1 on 2024-09-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineInventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='quantityAvailable',
            field=models.IntegerField(default=1, verbose_name='Cantidad disponible'),
            preserve_default=False,
        ),
    ]
