# Generated by Django 5.1 on 2024-09-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.FloatField(verbose_name='Celular'),
        ),
    ]
