# Generated by Django 5.1 on 2024-09-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_employees_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Contraseña'),
        ),
    ]
