# Generated by Django 5.1 on 2024-09-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='emergency_contact_phone',
            field=models.CharField(default='000-000-0000', max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='patients',
            name='policy_number',
            field=models.CharField(default='000-000-0000', max_length=20, verbose_name='Policy Number'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='emergency_contact',
            field=models.CharField(max_length=50, verbose_name='Emergency Contact'),
        ),
    ]
