# Generated by Django 5.1 on 2024-09-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_patients_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='policy_number',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Policy Number'),
        ),
    ]
