# Generated by Django 5.1 on 2024-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PROGR', 'Programada'), ('COMPL', 'Completada'), ('CANCEL', 'Cancelada')], default='PROGR', max_length=20, verbose_name='Status'),
        ),
    ]
